--- # Install CAserver
- hosts: localhost
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Installing Git
      apt:
        name: git
        state: latest
    - name: Add an Apt signing key for openpki, uses whichever key is at the URL
      apt_key:
        url: https://packages.openxpki.org/v2/debian/Release.key
        validate_certs: False
        state: present
